apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fleetman-webapp
  name: fleetman-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: fleetman-webapp
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: fleetman-webapp
    spec:
      containers:
        - image: supinfo4kube/web-app:1.0.0-dockercompose
          name: fleetman-webapp
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
