apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fleetman-api-gateway
  name: fleetman-api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: fleetman-api-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: fleetman-api-gateway
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice
          image: supinfo4kube/api-gateway:1.0.1
          name: fleetman-api-gateway
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
