apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fleetman-webapp
  name: fleetman-webapp
spec:
  type: NodePort
  ports:
    - name: "30080"
      port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    io.kompose.service: fleetman-webapp
