apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fleetman-webapp
  name: fleetman-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: fleetman-webapp
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: fleetman-webapp
    spec:
      containers:
        - image: supinfo4kube/web-app:1.0.0
          name: fleetman-webapp
          requests:
              memory: "256Mi"  # Demande de mémoire
              cpu: "0.5"       # Demande de CPU
          limits:
              memory: "512Mi"  # Limite mémoire
              cpu: "1"         # Limite CPU
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
