apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    io.kompose.service: mongo-data
  name: mongo-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mongo
